# Generated by Django 2.2.13 on 2022-06-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero1', models.CharField(max_length=50)),
                ('numero2', models.CharField(max_length=50)),
                ('resultado', models.CharField(max_length=50)),
            ],
        ),
    ]
