# Generated by Django 2.2.13 on 2022-06-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.CharField(max_length=50)),
                ('x', models.CharField(max_length=50)),
            ],
        ),
    ]
