# Generated by Django 2.2.13 on 2022-06-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_dataframe_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataframe_model',
            name='Dataframe',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataframe_model',
            name='bootstrap',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=5),
        ),
    ]
