# Generated by Django 2.2.13 on 2022-06-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20220625_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataframe_model',
            name='image',
        ),
        migrations.AddField(
            model_name='dataframe_model',
            name='report',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
